server:
  port: 80

spring:
  profiles:
    default: dev

  datasource:
    url: jdbc:mysql://localhost:3306/hanghae
    username: hanghae
    password: Hanghae1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
